name             "incron"
maintainer       "David Radcliffe"
maintainer_email "radcliffe.david@gmail.com"
license          "MIT"
description      "Installs incron."
long_description "See README.md"
version          "0.1.0"

supports "redhat"
supports "centos"
